name: Update and clean blocklist

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Download blocklist
        run: |
          curl -L -o raw_list.txt \
          "https://raw.githubusercontent.com/sjhgvr/oisd/main/domainswild2_small.txt"

      - name: Remove comments and empty lines
        run: |
          grep -v '^#' raw_list.txt | \
          grep -v '^[[:space:]]*$' > blocklist.txt

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add blocklist.txt

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Auto-update blocklist $(date +'%Y-%m-%d')"
          git push
